### ISSUE TITLE
&& 연산자로 if 문을 대체하는 것에 대한 질문입니다!!

### ISSUE THREAD

**Issue by hsh2001** [dangen-effy/modern-javascript#2]
우선 좋은 글 감사합니다. 🙇 

https://github.com/dangen-effy/modern-javascript#truthy-and-falsy

이 부분에서, 아래와 같은 방법이 심플하지 못하다고 하셨고,
```javascript
if (movie.ironman.ko) {
  console.log('한글 자막 개봉')
}
```

그래서 아래와 같은 코드로 대체하길 추천하셨습니다.
```javascript
movie.ironman.ko && console.log('한글 자막 개봉')
```

물론 아래의 방법이 보이기에는 더욱 심플하고 짧아보이며 완전히 같은 기능을 하지만, 코드를 작성하는데 중요한 요소 중 하나인 가독성이나 직관성이 떨어진다고 생각합니다. if **구문**은 참 거짓에 따른 코드의 분기점 기능을 하고 AND **연산자**는 말그대로 두 값을 정해진 규칙에 따라 연산하는 역할을 합니다. 그런데 이러한 연산자를 코드의 분기점으로써 사용하는 것은 가독성이나 직관성 측면에서 떨어진다고 생각합니다. (물론 좋은 코드에 대한 생각은 모두 다르기에 정답이라는 것은 없습니다!! 제 생각일 뿐입니다.) 혹시 AND 연산자를 if 문으로 바꾼 이유를 알려주실 수 있을까요? 단순히 짧고 심플하기 때문인가요? 그리고 AND 연산자가 if문과 같은 결과를 낼 수 있는 이유도 간단하게 적어주시면 왜 그렇게 대체될 수 있는지 모르시는 분들에게 도움이 될 것 같아요.

감사합니다 😄

**Comment by effy-coding** [comment]
맞습니다. [Truthy and Falsy](https://github.com/dangen-effy/modern-javascript#truthy-and-falsy) 단원에서 말씀하신 `AND`, `OR` 연산자들 즉 `short-circuit` 을 다루는 건 범위를 조금 벗어나지 않았나라는 생각이 드네요. 제 코딩 스타일이 저도 모르게 개입된 점도 있습니다. 모던 자바스크립트는 좀 더 범용적인 사례를 소개해야 하니,

지적해주신

```js
movie.ironman.ko && console.log('한글 자막 개봉')
```

코드 블록은 제거해서 `Truth and Falsy` 단원이 다루는 내용의 범위를 명확히 할 수 있을 거 같습니다. 😇

**Comment by effy-coding** [comment]
@hsh2001 

https://github.com/dangen-effy/modern-javascript/pull/3

이렇게 수정하면 될까요?

**Comment by hsh2001** [comment]
제가 PR에 제 커밋 추가하는 방법을 몰라서 ㅠㅜ 댓글로 남길게요! 

이것도 
```javascript
iAmNotArray.forEach && iAmNotArray.forEach(it => console.log(it))
```

이렇게 바꾸는건 어떨까요??
```javascript
if (iAmNotArray.forEach) { 
  iAmNotArray.forEach(it => console.log(it))
}
```

**Comment by effy-coding** [comment]
오호 그렇군요. 그럼 그곳도 수정해서 머지 하겠습니다. ㅎㅎ
