### ISSUE TITLE
잘못된 분류

### ISSUE THREAD

**Issue by joonseokhu** [dangen-effy/modern-javascript#4]
[이 부분](https://github.com/dangen-effy/modern-javascript?fbclid=IwAR05yW98SjRHoCjS3wzziNiqQeRL6bTsIWdohGTUMJnFsAVQv-q8TKrDZjk#2-%EB%B0%B0%EC%97%B4-%EA%B5%AC%EC%A1%B0-%EB%B6%84%ED%95%B4-%ED%95%A0%EB%8B%B9)이 잘못 분류되었습니다.

구조분해할당 (destructuring assignment) 문법이 아니고,
전개구문(spread syntax) 입니다.

**TL;DR**
- 구조분해할당은 변수를 선언하는 문법입니다.
- 전개구문은 값을 만들때 쓰는 구문입니다.
- 구조분해할당의 `...` 구문과 전개구문은 같은 모양이지만 정 반대의 동작을 합니다.

## 구조분해할당(Destructuring Assignment), 나머지 요소(Rest Element)

구조분해할당은 기존 객체/배열에 있는 요소들을 분해해서 해당 스코프의 새로운 변수로 선언하는것 입니다.
구조분해할당에서 사용되는 `...` 문은 나머지 요소(rest element) 라고 불립니다.

선언하고 남은 요소들을 하나의 변수에 모아두겠다는 뜻입니다.

나머지요소에서 명시한 변수명이 선언되는 효과를 가지며,
나머지 요소, 나머지 인자 등의 나머지 구문은 맨 마지막에 한번만 위치할 수 있습니다.

```js
const obj = {a: 1, b: 2, c: 3}
const arr = {4, 5, 6}

const { a, ...restOfObj } = obj
const [ four, ...restOfArr ] = arr

// restOfObj === {b: 2, c: 3}
// restOfArr === [5, 6]
```

## 전개구문 (Spread Syntax)

전개구문은 객체/배열의 나머지 요소들을 `...` 문을 사용해서, 어떤 객체/배열을 해당 리터럴에 풀어놓겠다는 뜻입니다.
해당 구문으로 변수가 선언되지 않으며, 리터럴상 앞쪽이나 뒤 어디든 위치가 가능하며, 하나의 리터럴에 여러번 등장하는것도 가능합니다.

```js
const obj = {a: 1, b: 2, c: 3}
const arr = {4, 5, 6}

const nextObj = { ...obj, d: 4 }
const nextArr = [ ...arr,  7, 8, ...arr ]

nextObj === { a: 1, b: 2, c: 3, d: 4 }
nextArr === [ 4, 5, 6, 7, 8, 4, 5, 6 ]
```

## 자료

- [mdn](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Spread_syntax#%EB%B0%B0%EC%97%B4_%EB%B3%B5%EC%82%AC)
- [v8](https://v8.dev/features/object-rest-spread)

**Comment by effy-coding** [comment]
@vraimentres 

https://github.com/dangen-effy/modern-javascript/pull/5

이렇게 수정해봤습니다.
